politifact:
  feature: bert
  lr: 0.00015
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 80
  max_epoch_f: 500
  mask_rate: 0.5
  num_layers: 2
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: mse
  optimizer: adam
  replace_rate: 0.0
  drop_edge_rate: 0.2
  alpha_l: 1
  norm: batchnorm
  residual: False
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 32

gossipcop:
  feature: bert
  lr: 0.00015
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 60
  max_epoch_f: 500
  mask_rate: 0.5
  num_layers: 2
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: mse
  optimizer: adam
  replace_rate: 0.0
  drop_edge_rate: 0.1
  alpha_l: 1
  norm: batchnorm
  residual: False
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 32
  alpha_l: 1